repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: MyPy Type Checking
        entry: mypy
        language: system
        args: [--ignore-missing-imports, .]
        pass_filenames: false
        types: [python]
        stages: [commit]

  - repo: local
    hooks:
      - id: django-tests
        name: Django Tests
        entry: pytest
        language: system
        pass_filenames: false
        types: [python]
        stages: [commit]
