# Generated by Django 5.1.2 on 2025-07-19 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('Cerro', 'CERRO'), ('Nueva Cba', 'NUEVA CBA')], max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Find Appointment',
                'verbose_name_plural': 'Find Appointments',
                'ordering': ['doctor_name'],
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Auth',
                'verbose_name_plural': 'User Auths',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='BestAppointmentFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('appointment_wanted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.findappointment')),
            ],
        ),
    ]
