# Generated by Django 5.1.2 on 2025-07-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauth',
            options={'ordering': ['docid'], 'verbose_name': 'User Auth', 'verbose_name_plural': 'User Auths'},
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='user',
            new_name='docid',
        ),
        migrations.AddField(
            model_name='userauth',
            name='name',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userauth',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
