# Generated by Django 5.1.2 on 2025-07-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_userauth_options_rename_user_userauth_docid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(db_index=True, max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
                ('servicio', models.CharField(max_length=255)),
                ('sucursal', models.CharField(max_length=255)),
                ('id_recurso', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo_recurso', models.IntegerField()),
                ('id_especialidad', models.IntegerField()),
                ('id_sucursal', models.IntegerField()),
                ('id_servicio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteAllende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_paciente', models.CharField(max_length=255)),
                ('docid', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente Allende',
                'verbose_name_plural': 'Pacientes Allende',
                'ordering': ['id_paciente'],
            },
        ),
        migrations.CreateModel(
            name='TipoDeTurno',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id_tipo_turno', models.IntegerField(primary_key=True, serialize=False)),
                ('id_servicio', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAuth',
        ),
        migrations.AlterModelOptions(
            name='findappointment',
            options={'ordering': ['doctor'], 'verbose_name': 'Find Appointment', 'verbose_name_plural': 'Find Appointments'},
        ),
        migrations.RemoveField(
            model_name='findappointment',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='findappointment',
            name='location',
        ),
        migrations.AddField(
            model_name='findappointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turnos.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='findappointment',
            name='tipo_de_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turnos.tipodeturno'),
            preserve_default=False,
        ),
    ]
