# Generated by Django 5.1.2 on 2025-07-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_doctor_pacienteallende_tipodeturno_delete_userauth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteallende',
            name='token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
