# Generated by Django 5.1.2 on 2025-07-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_alter_pacienteallende_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteallende',
            name='token',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
