# Generated by Django 5.1.2 on 2025-07-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorio_allende', '0002_alter_pacienteallende_id_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(default='expo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Device Registration',
                'verbose_name_plural': 'Device Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
