# Generated by Django 5.1.2 on 2025-08-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sanatorio_allende",
            "0004_bestappointmentfound_patient_deviceregistration_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="findappointment",
            name="desired_timeframe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1 week", "1 week"),
                    ("2 weeks", "2 weeks"),
                    ("3 weeks", "3 weeks"),
                    ("anytime", "anytime"),
                ],
                default="anytime",
                max_length=255,
                null=True,
            ),
        ),
    ]
