# Generated by Django 5.1.2 on 2025-08-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanatorio_allende", "0005_findappointment_desired_timeframe"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestappointmentfound",
            name="not_interested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bestappointmentfound",
            name="appointment_wanted",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sanatorio_allende.findappointment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bestappointmentfound",
            unique_together={("appointment_wanted", "patient", "datetime")},
        ),
    ]
