# Generated by Django 5.1.2 on 2025-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanatorio_allende", "0006_bestappointmentfound_not_interested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestappointmentfound",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bestappointmentfound",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bestappointmentfound",
            name="duracion_individual",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bestappointmentfound",
            name="hora",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="bestappointmentfound",
            name="id_item_plantilla",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bestappointmentfound",
            name="id_plantilla_turno",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bestappointmentfound",
            name="requisito_administrativo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
