# Generated by Django 5.1.2 on 2025-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanatorio_allende", "0007_bestappointmentfound_confirmed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bestappointmentfound",
            name="requisito_administrativo",
        ),
        migrations.AddField(
            model_name="pacienteallende",
            name="id_financiador",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pacienteallende",
            name="id_plan",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
