# Generated by Django 5.1.2 on 2025-08-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sanatorio_allende",
            "0008_remove_bestappointmentfound_requisito_administrativo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmenttype",
            name="id_tipo_prestacion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bestappointmentfound",
            name="confirmed_id_turno",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
