# Generated by Django 5.1.2 on 2025-08-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sanatorio_allende", "0009_appointmenttype_id_tipo_prestacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bestappointmentfound",
            name="hora",
        ),
    ]
