# Generated by Django 5.1.2 on 2025-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanatorio_allende", "0010_remove_bestappointmentfound_hora"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="findappointment",
            options={
                "ordering": ["doctor_name"],
                "verbose_name": "Find Appointment",
                "verbose_name_plural": "Find Appointments",
            },
        ),
        migrations.RemoveField(
            model_name="findappointment",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="findappointment",
            name="tipo_de_turno",
        ),
        migrations.AddField(
            model_name="findappointment",
            name="doctor_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="especialidad",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="id_especialidad",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="id_recurso",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="id_servicio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="id_sucursal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="id_tipo_prestacion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="id_tipo_recurso",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="nombre_tipo_prestacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="servicio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="findappointment",
            name="sucursal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
