# Generated by Django 5.1.2 on 2025-08-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanatorio_allende", "0011_alter_findappointment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="findappointment",
            name="id_prestacion",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
