# Generated by Django 5.1.2 on 2025-08-17 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanatorio_allende", "0012_findappointment_id_prestacion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctor",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="especialidad",
        ),
        migrations.AlterUniqueTogether(
            name="especialidad",
            unique_together=None,
        ),
        migrations.AlterField(
            model_name="bestappointmentfound",
            name="patient",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="sanatorio_allende.pacienteallende",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="doctor_name",
            field=models.CharField(db_index=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="especialidad",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="id_especialidad",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="id_prestacion",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="id_recurso",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="id_servicio",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="id_sucursal",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="id_tipo_prestacion",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="id_tipo_recurso",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="nombre_tipo_prestacion",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="patient",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="sanatorio_allende.pacienteallende",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="servicio",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findappointment",
            name="sucursal",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AppointmentType",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Especialidad",
        ),
    ]
